
version: "3.7"

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    #ports:
     # - 8000:8000
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db

  db:
    image: "${DB_IMAGE}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web



volumes:
  static_volume:
  media_volume:
  postgres_data:
